const projectsEl=document.getElementById('projectGrid'),filtersEl=document.getElementById('filters');let projects=[],active='All';
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderFilters(){const cats=['All',...new Set(projects.map(p=>p.category))];filtersEl.innerHTML=cats.map(c=>`<button class="filter ${c===active?'active':''}" data-c="${esc(c)}">${esc(c)}</button>`).join('');filtersEl.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.c;renderFilters();renderProjects();})}
function renderProjects(){const list=active==='All'?projects:projects.filter(p=>p.category===active);projectsEl.innerHTML=list.map(p=>`<article class="card"><div class="card-visual" aria-hidden="true"></div><div class="card-body"><h3>${esc(p.title)}</h3><div class="meta">${esc(p.meta)}</div><p>${esc(p.description)}</p>${p.url?`<a href="${esc(p.url)}" target="_blank" rel="noreferrer">[ ${esc(p.cta)} ]</a>`:`<span class="disabled">[ ${esc(p.cta)} ]</span>`}</div></article>`).join('')}
fetch('/data/projects.json').then(r=>r.json()).then(d=>{projects=d;renderFilters();renderProjects()});
const menuButton=document.getElementById('menuButton'),menu=document.getElementById('menu');menuButton.onclick=()=>{const o=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',o)};menu.querySelectorAll('a').forEach(a=>a.onclick=()=>menu.classList.remove('open'));
const panel=document.getElementById('customizer');document.getElementById('customizeOpen').onclick=()=>panel.classList.add('open');document.getElementById('customizeClose').onclick=()=>panel.classList.remove('open');
const pink=document.getElementById('pinkColor'),cyan=document.getElementById('cyanColor'),bg=document.getElementById('bgColor'),scan=document.getElementById('scanlinesToggle');
function apply(){document.documentElement.style.setProperty('--pink',pink.value);document.documentElement.style.setProperty('--cyan',cyan.value);document.documentElement.style.setProperty('--bg',bg.value);document.querySelector('.scanlines').classList.toggle('off',!scan.checked)}
function load(){pink.value=localStorage.md_pink||'#ff2baa';cyan.value=localStorage.md_cyan||'#37ecff';bg.value=localStorage.md_bg||'#050407';scan.checked=localStorage.md_scan!=='false';apply()}
pink.oninput=()=>{apply();localStorage.md_pink=pink.value};cyan.oninput=()=>{apply();localStorage.md_cyan=cyan.value};bg.oninput=()=>{apply();localStorage.md_bg=bg.value};scan.onchange=()=>{apply();localStorage.md_scan=scan.checked};
document.getElementById('resetTheme').onclick=()=>{['md_pink','md_cyan','md_bg','md_scan'].forEach(k=>localStorage.removeItem(k));load()};load();